# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be385960e4fe46c8273fdd9e23e4a284bf63f56adfca1a9c84a4cf8eccbdfc85649916dee511e3e342fe8239aae567ae2804fa6d7cc536186824f3c4aa4b947

test:
  secret_key_base: 666eebc8906b3859ab637c026dac2a52a9740ab46d1de7e5fc5ed3c9263895273717ab92f608a3c35b1c69c8a55677e27f91a17b178b42a18b85eb8baed8d349

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
